//! Knowledge graph entities.

use crate::temporal::BiTemporalInterval;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use crate::id::EntityId;

/// A node in the knowledge graph.
///
/// Entities are the fundamental units of knowledge in Gallifrey. They represent
/// objects, concepts, or people.
///
/// # Examples
///
/// Creating a simple entity representing a person:
///
/// ```
/// use tardis_common::domain::Entity;
/// use tardis_common::id::EntityId;
/// use tardis_common::temporal::BiTemporalInterval;
/// use std::collections::HashMap;
/// use serde_json::json;
///
/// let entity = Entity {
///     id: EntityId::new(),
///     entity_type: "Person".to_string(),
///     name: "The Doctor".to_string(),
///     properties: {
///         let mut props = HashMap::new();
///         props.insert("species".to_string(), json!("Time Lord"));
///         props.insert("origin".to_string(), json!("Gallifrey"));
///         props
///     },
///     embedding: None, // Generated by Vortex later
///     temporal: BiTemporalInterval::now(),
///     source: Some("manual_entry".to_string()),
/// };
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entity {
    /// Unique identifier.
    pub id: EntityId,
    /// Entity type (e.g., "Concept", "Person", "Project").
    ///
    /// This categorizes the entity for schema validation and querying.
    pub entity_type: String,
    /// The primary name or label of the entity.
    pub name: String,
    /// Arbitrary properties stored as a JSON object.
    ///
    /// This allows flexible schema evolution without changing the struct definition.
    pub properties: HashMap<String, serde_json::Value>,
    /// Embedding vector for semantic search.
    ///
    /// Generated by the Vortex inference engine to allow vector similarity queries.
    pub embedding: Option<Vec<f32>>,
    /// Temporal metadata tracking both valid time and transaction time.
    ///
    /// See [`BiTemporalInterval`] for details on how history is tracked.
    pub temporal: BiTemporalInterval,
    /// Source of this knowledge (e.g., "user", "`file_import`", "inference").
    pub source: Option<String>,
}

/// A relationship between entities.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Relationship {
    /// Unique identifier.
    pub id: EntityId,
    /// Relationship type (e.g., "KNOWS", "CONTAINS", "`DEPENDS_ON`").
    pub relationship_type: String,
    /// Source entity ID.
    pub source: EntityId,
    /// Target entity ID.
    pub target: EntityId,
    /// Relationship properties.
    pub properties: HashMap<String, serde_json::Value>,
    /// Temporal metadata.
    pub temporal: BiTemporalInterval,
}
