//! Domain entities shared across Tardis OS.

use tardis_common::id::{EntityId, SessionId, SnapshotId};
use tardis_common::temporal::BiTemporalInterval;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ============================================================================
// Knowledge Graph
// ============================================================================

/// A node in the knowledge graph.
///
/// Entities are the fundamental units of knowledge in Gallifrey. They represent
/// objects, concepts, or people.
///
/// # Examples
///
/// Creating a simple entity representing a person:
///
/// ```
/// use tardis_gallifrey::domain::Entity;
/// use tardis_common::id::EntityId;
/// use tardis_common::temporal::BiTemporalInterval;
/// use std::collections::HashMap;
/// use serde_json::json;
///
/// let entity = Entity {
///     id: EntityId::new(),
///     entity_type: "Person".to_string(),
///     name: "The Doctor".to_string(),
///     properties: {
///         let mut props = HashMap::new();
///         props.insert("species".to_string(), json!("Time Lord"));
///         props.insert("origin".to_string(), json!("Gallifrey"));
///         props
///     },
///     embedding: None, // Generated by Vortex later
///     temporal: BiTemporalInterval::now(),
///     source: Some("manual_entry".to_string()),
/// };
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entity {
    /// Unique identifier.
    pub id: EntityId,
    /// Entity type (e.g., "Concept", "Person", "Project").
    ///
    /// This categorizes the entity for schema validation and querying.
    pub entity_type: String,
    /// The primary name or label of the entity.
    pub name: String,
    /// Arbitrary properties stored as a JSON object.
    ///
    /// This allows flexible schema evolution without changing the struct definition.
    pub properties: HashMap<String, serde_json::Value>,
    /// Embedding vector for semantic search.
    ///
    /// Generated by the Vortex inference engine to allow vector similarity queries.
    pub embedding: Option<Vec<f32>>,
    /// Temporal metadata tracking both valid time and transaction time.
    ///
    /// See [`BiTemporalInterval`] for details on how history is tracked.
    pub temporal: BiTemporalInterval,
    /// Source of this knowledge (e.g., "user", "`file_import`", "inference").
    pub source: Option<String>,
}

/// A relationship between entities.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Relationship {
    /// Unique identifier.
    pub id: EntityId,
    /// Relationship type (e.g., "KNOWS", "CONTAINS", "`DEPENDS_ON`").
    pub relationship_type: String,
    /// Source entity ID.
    pub source: EntityId,
    /// Target entity ID.
    pub target: EntityId,
    /// Relationship properties.
    pub properties: HashMap<String, serde_json::Value>,
    /// Temporal metadata.
    pub temporal: BiTemporalInterval,
}

// ============================================================================
// Conversation
// ============================================================================

/// Role in a conversation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Role {
    /// User message.
    User,
    /// Assistant response.
    Assistant,
    /// System message.
    System,
}

/// A message in a conversation.
///
/// Represents a single turn in a dialogue between the user and the system.
///
/// # Examples
///
/// ```
/// use tardis_gallifrey::domain::{Message, Role};
/// use tardis_common::id::{EntityId, SessionId};
/// use chrono::Utc;
///
/// let message = Message {
///     id: EntityId::new(),
///     session_id: SessionId::new(),
///     role: Role::User,
///     content: "Explain the bootstrap paradox.".to_string(),
///     timestamp: Utc::now(),
///     embedding: None,
///     entity_refs: vec![],
/// };
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Unique identifier for this message.
    pub id: EntityId,
    /// The session this message belongs to.
    ///
    /// Messages are grouped by session to maintain conversation context.
    pub session_id: SessionId,
    /// The role of the speaker (User, Assistant, System).
    pub role: Role,
    /// The text content of the message.
    pub content: String,
    /// When the message was created.
    pub timestamp: DateTime<Utc>,
    /// Embedding vector for semantic search over chat history.
    ///
    /// Allows finding past conversations about specific topics even if keywords differ.
    pub embedding: Option<Vec<f32>>,
    /// IDs of entities mentioned or relevant to this message.
    ///
    /// Linked by the `Chronos` analysis pipeline to connect chat to the knowledge graph.
    pub entity_refs: Vec<EntityId>,
}

/// A conversation session.
///
/// Tracks the lifecycle of a user interaction, including topics discussed
/// and metadata for context retrieval.
///
/// # Examples
///
/// ```
/// use tardis_gallifrey::domain::Session;
/// use tardis_common::id::SessionId;
/// use chrono::Utc;
/// use std::collections::HashMap;
///
/// let session = Session {
///     id: SessionId::new(),
///     started_at: Utc::now(),
///     ended_at: None,
///     summary: None,
///     topics: vec!["Physics".to_string(), "Time Travel".to_string()],
///     metadata: HashMap::new(),
/// };
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Session {
    /// Unique identifier.
    pub id: SessionId,
    /// Session start time.
    pub started_at: DateTime<Utc>,
    /// Session end time (None if active).
    pub ended_at: Option<DateTime<Utc>>,
    /// Session summary (generated after session ends).
    pub summary: Option<String>,
    /// Topics discussed.
    pub topics: Vec<String>,
    /// Session metadata.
    pub metadata: HashMap<String, serde_json::Value>,
}

// ============================================================================
// System State
// ============================================================================

/// A snapshot of system state.
///
/// Captures a frozen point-in-time view of the OS, allowing for
/// time-travel debugging and rollback.
///
/// # Examples
///
/// ```
/// use tardis_gallifrey::domain::{Snapshot, SnapshotTrigger, SystemState};
/// use tardis_common::id::SnapshotId;
/// use chrono::Utc;
/// use std::collections::HashMap;
///
/// let snapshot = Snapshot {
///     id: SnapshotId::new(),
///     name: "Pre-Update Backup".to_string(),
///     timestamp: Utc::now(),
///     trigger: SnapshotTrigger::Manual,
///     state: SystemState {
///         processes: HashMap::new(),
///         config: HashMap::new(),
///         files: HashMap::new(),
///     },
///     checksum: "sha256:abc123...".to_string(),
/// };
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Snapshot {
    /// Unique identifier.
    pub id: SnapshotId,
    /// Snapshot name (user-provided or auto-generated).
    pub name: String,
    /// When the snapshot was taken.
    pub timestamp: DateTime<Utc>,
    /// What triggered the snapshot.
    pub trigger: SnapshotTrigger,
    /// Captured state.
    pub state: SystemState,
    /// Checksum for integrity.
    pub checksum: String,
}

/// What triggered a snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SnapshotTrigger {
    /// Scheduled snapshot.
    Scheduled,
    /// User-requested snapshot.
    Manual,
    /// Before a significant operation.
    PreOperation(String),
    /// After an error.
    Error(String),
}

/// Captured system state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemState {
    /// Process states.
    pub processes: HashMap<u32, ProcessState>,
    /// Configuration values.
    pub config: HashMap<String, serde_json::Value>,
    /// File system snapshot (paths and metadata).
    pub files: HashMap<String, FileMetadata>,
}

/// Process state information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessState {
    /// Process ID.
    pub pid: u32,
    /// Process name.
    pub name: String,
    /// Process status.
    pub status: String,
    /// Memory usage.
    pub memory_bytes: u64,
    /// CPU usage percentage.
    pub cpu_percent: f32,
}

/// File metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileMetadata {
    /// File path.
    pub path: String,
    /// File size.
    pub size: u64,
    /// Last modified time.
    pub modified: DateTime<Utc>,
    /// File hash (for content tracking).
    pub hash: Option<String>,
}

/// A change between snapshots.
///
/// Represents a diff operation on the system state, used for
/// audit logging and visualizing evolution over time.
///
/// # Examples
///
/// ```
/// use tardis_gallifrey::domain::{Change, ChangeType};
/// use chrono::Utc;
/// use serde_json::json;
///
/// let change = Change {
///     timestamp: Utc::now(),
///     path: "/etc/tardis/config.toml".to_string(),
///     change_type: ChangeType::Update,
///     old_value: Some(json!({ "debug": false })),
///     new_value: Some(json!({ "debug": true })),
/// };
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Change {
    /// When the change occurred.
    pub timestamp: DateTime<Utc>,
    /// What changed.
    pub path: String,
    /// Type of change.
    #[allow(clippy::struct_field_names)]
    pub change_type: ChangeType,
    /// Old value (if applicable).
    pub old_value: Option<serde_json::Value>,
    /// New value (if applicable).
    pub new_value: Option<serde_json::Value>,
}

/// Type of change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ChangeType {
    /// Created.
    Create,
    /// Updated.
    Update,
    /// Deleted.
    Delete,
}
