//! The Dreamer: Memory Consolidation Engine.
//!
//! "We are such stuff as dreams are made on."
//!
//! This module processes conversation history (short-term memory) and consolidates
//! it into the Knowledge Graph (long-term memory) by extracting key entities and facts.

use crate::error::{ChronosError, ChronosResult};
use crate::experimental::psychic_paper::{Intent, PsychicPaper};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::sync::Arc;
use tardis_common::id::EntityId;
use tardis_common::temporal::BiTemporalInterval;
use tardis_common::SessionId;
use tardis_gallifrey::domain::Entity;
use tardis_gallifrey::Gallifrey;
use tardis_vortex::config::InferenceParams;
use tardis_vortex::{ModelHandle, Vortex};
use tracing::{info, instrument};

/// The Dreamer engine.
#[derive(Debug)]
pub struct Dreamer {
    gallifrey: Arc<Gallifrey>,
    vortex: Arc<Vortex>,
    model: ModelHandle,
    paper: PsychicPaper,
}

/// A simplified entity structure for LLM generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct DreamEntity {
    name: String,
    #[serde(rename = "type")]
    entity_type: String,
    description: String,
    properties: HashMap<String, Value>,
}

impl Dreamer {
    /// Create a new Dreamer engine.
    #[must_use]
    pub const fn new(
        gallifrey: Arc<Gallifrey>,
        vortex: Arc<Vortex>,
        model: ModelHandle,
    ) -> Self {
        Self {
            gallifrey,
            vortex,
            model,
            paper: PsychicPaper::new(),
        }
    }

    /// Consolidate memories from a session.
    ///
    /// # Errors
    ///
    /// Returns an error if the process fails.
    #[instrument(skip(self))]
    pub async fn dream(&self, session_id: SessionId) -> ChronosResult<Vec<EntityId>> {
        info!("Dreamer: Consolidating memories for session {}", session_id);

        // 1. Fetch recent conversation history
        let messages = self
            .gallifrey
            .conversation()
            .get_recent_messages(session_id, 20)
            .map_err(|e| ChronosError::Common(e.into()))?;

        if messages.is_empty() {
            info!("Dreamer: No messages to dream about.");
            return Ok(Vec::new());
        }

        // 2. Construct prompt
        let mut transcript = String::new();
        for msg in &messages {
            use std::fmt::Write;
            let _ = writeln!(transcript, "{:?}: {}", msg.role, msg.content);
        }

        let prompt = format!(
            "CONVERSATION TRANSCRIPT:\n\
             {transcript}\n\n\
             TASK: Extract key facts, user preferences, and important entities from the above conversation.\n\
             Ignore trivial greetings. Focus on long-term knowledge.\n\
             Output a JSON list of objects. Each object must have:\n\
             - \"name\": (string) The name of the entity or concept.\n\
             - \"type\": (string) The category (e.g., \"Person\", \"Fact\", \"Preference\").\n\
             - \"description\": (string) A summary of what was learned.\n\
             - \"properties\": (object) Key-value pairs of details.\n\
             Example:\n\
             [\n  {{ \"name\": \"User\", \"type\": \"Person\", \"description\": \"The user likes blue.\", \"properties\": {{ \"favorite_color\": \"blue\" }} }}\n]\n\
             Output ONLY JSON."
        );

        // 3. Inference
        let params = InferenceParams::default()
            .with_temperature(0.3) // Be factual
            .with_max_tokens(1024);

        let response = self
            .vortex
            .infer(self.model, &prompt, params)
            .await
            .map_err(|e| ChronosError::Common(tardis_common::Error::Internal(e.to_string())))?;

        // 4. Parse output
        let parsed = self
            .paper
            .interpret(&response, Intent::Json)
            .map_err(|e| ChronosError::Common(tardis_common::Error::Internal(e)))?;

        let dream_entities: Vec<DreamEntity> = serde_json::from_value(parsed)
            .map_err(|e| ChronosError::Common(tardis_common::Error::Internal(e.to_string())))?;

        // 5. Insert into Gallifrey
        let mut created_ids = Vec::new();

        for de in dream_entities {
            // Check if entity already exists (by name)
            // Ideally we would do a semantic search or precise lookup,
            // but for now we just create a new one.
            // Gallifrey doesn't enforce name uniqueness, but we should try to avoid duplicates.
            // TODO: Implement dedup logic.

            let entity = Entity {
                id: EntityId::new(),
                entity_type: de.entity_type,
                name: de.name,
                properties: de.properties,
                embedding: None, // Will be generated by background worker eventually
                temporal: BiTemporalInterval::now(),
                source: Some("Dreamer".to_string()),
            };

            let id = self
                .gallifrey
                .insert(entity)
                .await
                .map_err(ChronosError::Common)?;

            created_ids.push(id);
        }

        info!("Dreamer: Created {} new knowledge entities.", created_ids.len());

        Ok(created_ids)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use serde_json::json;
    use tardis_gallifrey::domain::{Message, Role};
    use tardis_vortex::ModelLoadConfig;

    #[tokio::test]
    async fn test_dreamer_consolidates_memory() {
        let gallifrey = Arc::new(Gallifrey::new());
        let vortex = Arc::new(Vortex::new().unwrap());

        // Setup session and messages
        let session_id = gallifrey.conversation().create_session().unwrap();

        let msg1 = Message {
            id: EntityId::new(),
            session_id,
            role: Role::User,
            content: "My name is Nova and I like Rust.".to_string(),
            timestamp: Utc::now(),
            embedding: None,
            entity_refs: Vec::new(),
        };
        gallifrey.conversation().add_message(msg1).unwrap();

        // Mock Vortex
        vortex.set_mock_inference(Box::new(|_, _, _| {
            let json = json!([
                {
                    "name": "Nova",
                    "type": "Person",
                    "description": "The user identified as Nova.",
                    "properties": {
                        "likes": "Rust"
                    }
                }
            ]);
            Ok(json.to_string())
        }));

        // Register dummy model
        vortex.set_mock_load_model(Box::new(move |_, _| Ok(ModelHandle::new(1))));
        let handle = vortex
            .load_model("dummy", ModelLoadConfig::default())
            .await
            .unwrap();

        let dreamer = Dreamer::new(gallifrey.clone(), vortex, handle);

        let ids = dreamer.dream(session_id).await.unwrap();

        assert_eq!(ids.len(), 1);

        // Verify insertion
        let history = gallifrey.get_history(ids[0]).await.unwrap();
        let entity = &history[0];
        assert_eq!(entity.name, "Nova");
        assert_eq!(entity.entity_type, "Person");
        assert_eq!(entity.source.as_deref(), Some("Dreamer"));
    }
}
